import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'
import axios from 'axios'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [location, setLocation] = useState('');
  const [data, setData] = useState({});
  const [weather, setWeather] = useState();
  const [errorMessage, setErrorMessage] = useState('');

  var apiKey = '5ab95bd805c9ead26a754baf4b1c4277'
  var lang = "en";
  var units = "metric";
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${location}&units=${units}&appid=${apiKey}&lang=${lang}`

  const searchLocation = (event) => {
    if(event.key === "Enter") {
      axios.get(url)  
      .then((response) => {
        console.clear();
        setData(response.data)
        console.log(response.data);
        setWeather(response.data.weather)
        setErrorMessage("")
      }).catch(err => {
        console.log(err);
        setErrorMessage("please enter another location")
        setData({});
        setWeather()
      })
      setLocation('')
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <input className={styles.input}
        value={location}
        onChange={event => setLocation(event.target.value)}
        placeholder="Enter Location"
        onKeyDown={searchLocation}
        type="text"/>
        <div className={styles.title}>{data.name}</div>
        {
          weather && weather.map((w, index)=> {
            return (
              <div className={styles.feel} key={index}>
                <div className={styles.cont}>

                  <div className={styles.topcont}>
                  <div className={styles.temp}>{data.main.temp}°C</div>
              <div className={styles.cloud}>{w.main}</div>
                </div>
              <div className={styles.bottomcont}>
                <div className={styles.feel}>{w.description}</div>
              <div className={styles.feel}>Feels like {data.main.feels_like}°C</div>
              <div className={styles.wind}>Wind: {data.wind.speed}m/s</div>
              </div>
                </div>
                
              
              </div>
            )
        })
      }
      
      </main>
    </>
)}
